### ISSUE TITLE
Model consistently predicts roughly double the gt count 

### ISSUE THREAD

**Issue by DiogoRavasco** [Yiming-M/CLIP-EBC#11]
Firstly, thank you for work.

I'm using my own dataset of schools of mackerel.

I have:
1. performed the counts with a kernel size of 32
and got the following counts:
{"0": 540619407, "1": 15881807, "2": 2205292, "3": 172353, "4": 14813, "5": 1406, "6": 98}

2. I then set the dynamic bins with values:
[0, 0], [1, 1], [2, 2], [3, 4], [5, "inf"]

and average anchor points with values:
0, 1, 2, 3.079143648, 5.065159574

The evaluations report an MAE of 27.5, and the density maps are better than I expected from a localization point-of-view, but the predicted count are around double the ground truth count.
Thank you in advance if you have any feedback on what I may be doing wrong.
And again, thank you for making your work available.

**Comment by Yiming-M** [comment]
Hi @DiogoRavasco ,

Thanks for your feedback on counting mackerels.
I don't know what may have caused the issue you mentioned, but just wondering, did you follow this procedure to obtain the total count from an image:

1. Generate the predicted density map from the image (trivial);
2. Upsample the density map to match the resolution of the image;
3. Sum up the upsampled density map to obtain the total count value.

If so, it's the upsampling that changes the total count value. You need to either 1) obtain the total count from the originally produced density map, or 2) scale the upsampled density map by a factor so that the sum is preserved.

Let me if this solves your problem.

Best,
Yiming

**Comment by DiogoRavasco** [comment]
Thank you for the response.

I did maintain the originally produced density map. 
Seeing as it was a consistent factor I ended up down sampling the density map. 
It was more a curiosity of what I may have done wrong than an inability to find a work around.

But thank you for your time and expertise.

Regards.

**Comment by Yiming-M** [comment]
Hi @DiogoRavasco 

I will close this issue for now since we haven't found others reporting similar problems, but feel free to re-open it.

Many thanks,
Yiming
