### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by susu-source** [Yiming-M/CLIP-EBC#19]
您好，我想请问一下训练代码需要跑满2600轮吗？可以过程中看一些参数手动停止训练吗？谢谢

**Comment by Yiming-M** [comment]
Hi @susu-source ,

Based on my observation, the optimal validation performances of most models can be achieved within 1400 epochs. Setting the total number of training epochs to 2600 is due to the continuing decreases in loss. You can change this by passing any value that you'd like to use to `--total_epochs` in [trainer.py](https://github.com/Yiming-M/CLIP-EBC/blob/main/trainer.py).

Many thanks,
Yiming

**Comment by susu-source** [comment]
您好，

我想问一下您训练的设备是什么型号的显卡呢，还有就是我使用您的DMCount-EBC (based on VGG-19)在sha上训练然后在sha上测试结果rmse要比原文高3个点，而mae要比您的低一个点，影响这些的是因为显卡型号不同吗？其他的我没有做修改。

非常感谢

**Comment by Yiming-M** [comment]
Hi,

To reproduce the same results, please make sure to use the same preprocessing methods and the training recipes as provided. In this scenario, please consider to use
```
python trainer.py \
    --model vgg19_ae --input_size 448 --reduction 8 --truncation 4 --anchor_points average \
    --dataset sha \
    --count_loss dmcount
```
to run the experiments.

Regarding your question, both NVIDIA RTX 3090 and NVIDIA RTX A5000 were used to run all experiments so we are not very sure about which exact GPU model was used to train DMCount-EBC. Due to the **small size** of the ShanghaiTech A dataset and the **randomness** in GPUs, it's possible for different results to be produced every time. Hence, would you mind training the model multiple times, or using a larger dataset (e.g. NWPU)? 

Also, please note, testing models on different platforms can usually also provide different results. 

If you have any further questions, please reopen this issue.

Many thanks,
Yiming

**Comment by susu-source** [comment]
您好，我看您只有clip_resnet、clip_vit的实验没有做clip_vgg。是因为效果不好吗，您有尝试过吗？

**Comment by susu-source** [comment]
您好，我看您只有clip_resnet、clip_vit的实验没有做clip_vgg。是因为效果不好吗，您有尝试过吗？

**Comment by susu-source** [comment]
您好，我看您只有clip_resnet、clip_vit的实验没有做clip_vgg。是因为效果不好吗，您有尝试过吗？

非常感谢
