### ISSUE TITLE
Bird flock Count

### ISSUE THREAD

**Issue by kushiluv** [Yiming-M/CLIP-EBC#3]
Hey, I'm looking for a model which would help me give an estimate on the number of birds in a bird flock. If I use my personal dataset, could you guide me through how I can train this model? Thankyou

**Comment by Yiming-M** [comment]
Hi @kushiluv,

Our work is currently only aimed at counting people. However, if you are interested into estimating flock sizes, you may try the following steps:

1. Preprocess your data so that it's organized in the same way as crowd counting datasets. For example:

    ```
    Bird Data
    ├── train
    │   ├── images
    │   │   ├── 0001.jpg
    │   │   ├── 0002.jpg
    │   │   ├── ...
    │   ├── labels
    │   │   ├── 0001.npy
    │   │   ├── 0002.npy
    │   │   ├── ...
    ├── val
    │   ├── images
    │   │   ├── 0001.jpg
    │   │   ├── 0002.jpg
    │   │   ├── ...
    │   ├── labels
    │   │   ├── 0001.npy
    │   │   ├── 0002.npy
    │   │   ├── ...
    ```

    where the label files are the 2D coordinates of annotated dots.

2. Add your processed data name in [`datasets/crowd.py`](https://github.com/Yiming-M/CLIP-EBC/blob/main/datasets/crowd.py). The ground-truth density map will be automatically generated by `Crowd` from the provided image and the dot annotations, so don't worry about it.
3. If you are interested in using CLIP-based models, you may also need to change the text prompt in the `format_count` function from [`models/clip/utils.py`](https://github.com/Yiming-M/CLIP-EBC/blob/main/models/clip/utils.py) by replacing `"person"`/`"people"` with for example `"bird"`/`"birds"`.

Please keep me updated with the models' performances in bird counting.

Many thanks,
Yiming

**Comment by 969149731** [comment]
Hello, may I ask what software can be used to annotate data using my own dataset in order to obtain corresponding similar labels
The file for 0001.npy, thank you for your answer.

**Comment by Yiming-M** [comment]
> Hello, may I ask what software can be used to annotate data using my own dataset in order to obtain corresponding similar labels The file for 0001.npy, thank you for your answer.

Hi @969149731 ,

I don't have any experience in data annotation. Maybe you could try this one: https://github.com/Elin24/cclabeler, which is used to annotate the NPWU Crowd Counting dataset.

If you are interested, maybe you could also try zero-shot object counting, e.g., https://github.com/songrise/CLIP-Count

**Comment by 969149731** [comment]
> > Hello, may I ask what software can be used to annotate data using my own dataset in order to obtain corresponding similar labels The file for 0001.npy, thank you for your answer.
> 
> Hi @969149731 ,
> 
> I don't have any experience in data annotation. Maybe you could try this one: https://github.com/Elin24/cclabeler, which is used to annotate the NPWU Crowd Counting dataset.
> 
> If you are interested, maybe you could also try zero-shot object counting, e.g., https://github.com/songrise/CLIP-Count
> 
> Many thanks, Yiming

非常感谢你的回答和建议，谢谢！

**Comment by Yiming-M** [comment]
Hi @kushiluv ,

It's been two weeks that you haven't provided any feedbacks yet. Hence, I presume that the issue has been somewhat resolved, and I am going to close it now. However, please feel free to re-open it if you have further questions. 

Many thanks,
Yiming
